const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#5B4FE9",
    background: "#FAFAFA",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#5B4FE9",
    primaryForeground: "#FFFFFF",
    secondary: "#FF6B6B",
    secondaryForeground: "#FFFFFF",
    muted: "#F0EFF8",
    mutedForeground: "#9292B0",
    accent: "#FFD166",
    accentForeground: "#1A1A2E",
    success: "#00C896",
    successForeground: "#FFFFFF",
    error: "#FF3B30",
    errorForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#E8E8F0",
    input: "#E8E8F0",
    surface: "#F0EFFE",
    textSecondary: "#6B6B8E",
    info: "#4CC9F0",
  },
  dark: {
    text: "#F0EFFF",
    tint: "#7C6FEF",
    background: "#0F0F1A",
    foreground: "#F0EFFF",
    card: "#1A1A2E",
    cardForeground: "#F0EFFF",
    primary: "#7C6FEF",
    primaryForeground: "#FFFFFF",
    secondary: "#FF6B6B",
    secondaryForeground: "#FFFFFF",
    muted: "#252540",
    mutedForeground: "#9292B0",
    accent: "#FFD166",
    accentForeground: "#1A1A2E",
    success: "#00C896",
    successForeground: "#FFFFFF",
    error: "#FF5A50",
    errorForeground: "#FFFFFF",
    destructive: "#FF5A50",
    destructiveForeground: "#FFFFFF",
    border: "#2E2E4A",
    input: "#2E2E4A",
    surface: "#252540",
    textSecondary: "#9292B0",
    info: "#4CC9F0",
  },
  radius: 16,
};

export default colors;
